export const QUESTION_TYPES = {
  AYAH_AFTER: 'AYAH_AFTER',
  AYAH_BEFORE: 'AYAH_BEFORE',
  CONSTRUCT_AYAH: 'CONSTRUCT_AYAH',
  PART_AYAH_AFTER: 'PART_AYAH_AFTER',
  PART_AYAH_BEFORE: 'PART_AYAH_BEFORE',
  AYAH_BY_NUMBER: 'AYAH_BY_NUMBER',
  AYAH_TO_ARAB: 'AYAH_TO_ARAB',
  AYAH_TO_TRANSLATION: 'AYAH_TO_TRANSLATION',
  AYAH_TAFSIR: 'AYAH_TAFSIR',
  // mini game
  SURAH_NUMBER: 'SURAH_NUMBER',
  SURAH_TRANLATION: 'SURAH_TRANLATION',
}

export const LANGUAGES = {
  id: 'indonesia',
  en: 'english',
}